package config

type KeyboardKey int

const (
	kK_SP1  KeyboardKey = 41
	kK_SP2  KeyboardKey = 12
	kK_SP3  KeyboardKey = 13
	kK_SP4  KeyboardKey = 26
	kK_SP5  KeyboardKey = 27
	kK_SP6  KeyboardKey = 39
	kK_SP7  KeyboardKey = 40
	kK_SP8  KeyboardKey = 43
	kK_SP9  KeyboardKey = 51
	kK_SP10 KeyboardKey = 52
	kK_SP11 KeyboardKey = 53
	kK_SP12 KeyboardKey = 86

	kK_UP    KeyboardKey = 103
	kK_DOWN  KeyboardKey = 108
	kK_LEFT  KeyboardKey = 105
	kK_RIGHT KeyboardKey = 106

	kK_ESC KeyboardKey = 1
	kK_1   KeyboardKey = 2
	kK_2   KeyboardKey = 3
	kK_3   KeyboardKey = 4
	kK_4   KeyboardKey = 5
	kK_5   KeyboardKey = 6
	kK_6   KeyboardKey = 7
	kK_7   KeyboardKey = 8
	kK_8   KeyboardKey = 9
	kK_9   KeyboardKey = 10
	kK_0   KeyboardKey = 11
	kK_Q   KeyboardKey = 16
	kK_W   KeyboardKey = 17
	kK_E   KeyboardKey = 18
	kK_R   KeyboardKey = 19
	kK_T   KeyboardKey = 20
	kK_Y   KeyboardKey = 21
	kK_U   KeyboardKey = 22
	kK_I   KeyboardKey = 23
	kK_O   KeyboardKey = 24
	kK_P   KeyboardKey = 25
	kK_A   KeyboardKey = 30
	kK_S   KeyboardKey = 31
	kK_D   KeyboardKey = 32
	kK_F   KeyboardKey = 33
	kK_G   KeyboardKey = 34
	kK_H   KeyboardKey = 35
	kK_J   KeyboardKey = 36
	kK_K   KeyboardKey = 37
	kK_L   KeyboardKey = 38
	kK_Z   KeyboardKey = 44
	kK_X   KeyboardKey = 45
	kK_C   KeyboardKey = 46
	kK_V   KeyboardKey = 47
	kK_B   KeyboardKey = 48
	kK_N   KeyboardKey = 49
	kK_M   KeyboardKey = 50
	kK_F1  KeyboardKey = 59
	kK_F2  KeyboardKey = 60
	kK_F3  KeyboardKey = 61
	kK_F4  KeyboardKey = 62
	kK_F5  KeyboardKey = 63
	kK_F6  KeyboardKey = 64
	kK_F7  KeyboardKey = 65
	kK_F8  KeyboardKey = 66
	kK_F9  KeyboardKey = 67
	kK_F10 KeyboardKey = 68
	kK_F11 KeyboardKey = 87
	kK_F12 KeyboardKey = 88

	kK_NUMLOCK    KeyboardKey = 69
	kK_SCROLLLOCK KeyboardKey = 70
	kK_RESERVED   KeyboardKey = 0
	kK_MINUS      KeyboardKey = 12
	kK_EQUAL      KeyboardKey = 13
	kK_BACKSPACE  KeyboardKey = 14
	kK_TAB        KeyboardKey = 15
	kK_LEFTBRACE  KeyboardKey = 26
	kK_RIGHTBRACE KeyboardKey = 27
	kK_ENTER      KeyboardKey = 28
	kK_SEMICOLON  KeyboardKey = 39
	kK_APOSTROPHE KeyboardKey = 40
	kK_GRAVE      KeyboardKey = 41
	kK_BACKSLASH  KeyboardKey = 43
	kK_COMMA      KeyboardKey = 51
	kK_DOT        KeyboardKey = 52
	kK_SLASH      KeyboardKey = 53
	kK_SPACE      KeyboardKey = 57
	kK_CAPSLOCK   KeyboardKey = 58

	kK_KP0         KeyboardKey = 82
	kK_KP1         KeyboardKey = 79
	kK_KP2         KeyboardKey = 80
	kK_KP3         KeyboardKey = 81
	kK_KP4         KeyboardKey = 75
	kK_KP5         KeyboardKey = 76
	kK_KP6         KeyboardKey = 77
	kK_KP7         KeyboardKey = 71
	kK_KP8         KeyboardKey = 72
	kK_KP9         KeyboardKey = 73
	kK_KPMINUS     KeyboardKey = 74
	kK_KPPLUS      KeyboardKey = 78
	kK_KPDOT       KeyboardKey = 83
	kK_KPJPCOMMA   KeyboardKey = 95
	kK_KPENTER     KeyboardKey = 96
	kK_KPSLASH     KeyboardKey = 98
	kK_KPASTERISK  KeyboardKey = 55
	kK_KPEQUAL     KeyboardKey = 117
	kK_KPPLUSMINUS KeyboardKey = 118
	kK_KPCOMMA     KeyboardKey = 121

	kK_ZENKAKUHANKAKU   KeyboardKey = 85
	kK_102ND            KeyboardKey = 86
	kK_RO               KeyboardKey = 89
	kK_KATAKANA         KeyboardKey = 90
	kK_HIRAGANA         KeyboardKey = 91
	kK_HENKAN           KeyboardKey = 92
	kK_KATAKANAHIRAGANA KeyboardKey = 93
	kK_MUHENKAN         KeyboardKey = 94
	kK_SYSRQ            KeyboardKey = 99
	kK_LINEFEED         KeyboardKey = 101
	kK_HOME             KeyboardKey = 102
	kK_PAGEUP           KeyboardKey = 104
	kK_END              KeyboardKey = 107
	kK_PAGEDOWN         KeyboardKey = 109
	kK_INSERT           KeyboardKey = 110
	kK_DELETE           KeyboardKey = 111
	kK_MACRO            KeyboardKey = 112
	kK_MUTE             KeyboardKey = 113
	kK_VOLUMEDOWN       KeyboardKey = 114
	kK_VOLUMEUP         KeyboardKey = 115
	kK_POWER            KeyboardKey = 116 /* SC System Power Down */
	kK_PAUSE            KeyboardKey = 119
	kK_SCALE            KeyboardKey = 120 /* AL Compiz Scale (Expose) */

	kK_HANGEUL   KeyboardKey = 122
	kK_HANGUEL   KeyboardKey = kK_HANGEUL
	kK_HANJA     KeyboardKey = 123
	kK_YEN       KeyboardKey = 124
	kK_LEFTMETA  KeyboardKey = 125
	kK_RIGHTMETA KeyboardKey = 126
	kK_COMPOSE   KeyboardKey = 127

	kK_STOP           KeyboardKey = 128 /* AC Stop */
	kK_AGAIN          KeyboardKey = 129
	kK_PROPS          KeyboardKey = 130 /* AC Properties */
	kK_UNDO           KeyboardKey = 131 /* AC Undo */
	kK_FRONT          KeyboardKey = 132
	kK_COPY           KeyboardKey = 133 /* AC Copy */
	kK_OPEN           KeyboardKey = 134 /* AC Open */
	kK_PASTE          KeyboardKey = 135 /* AC Paste */
	kK_FIND           KeyboardKey = 136 /* AC Search */
	kK_CUT            KeyboardKey = 137 /* AC Cut */
	kK_HELP           KeyboardKey = 138 /* AL Integrated Help Center */
	kK_MENU           KeyboardKey = 139 /* Menu (show menu) */
	kK_CALC           KeyboardKey = 140 /* AL Calculator */
	kK_SETUP          KeyboardKey = 141
	kK_SLEEP          KeyboardKey = 142 /* SC System Sleep */
	kK_WAKEUP         KeyboardKey = 143 /* System Wake Up */
	kK_FILE           KeyboardKey = 144 /* AL Local Machine Browser */
	kK_SENDFILE       KeyboardKey = 145
	kK_DELETEFILE     KeyboardKey = 146
	kK_XFER           KeyboardKey = 147
	kK_PROG1          KeyboardKey = 148
	kK_PROG2          KeyboardKey = 149
	kK_WWW            KeyboardKey = 150 /* AL Internet Browser */
	kK_MSDOS          KeyboardKey = 151
	kK_COFFEE         KeyboardKey = 152 /* AL Terminal Lock/Screensaver */
	kK_SCREENLOCK     KeyboardKey = kK_COFFEE
	kK_ROTATE_DISPLAY KeyboardKey = 153 /* Display orientation for e.g. tablets */
	kK_DIRECTION      KeyboardKey = kK_ROTATE_DISPLAY
	kK_CYCLEWINDOWS   KeyboardKey = 154
	kK_MAIL           KeyboardKey = 155
	kK_BOOKMARKS      KeyboardKey = 156 /* AC Bookmarks */
	kK_COMPUTER       KeyboardKey = 157
	kK_BACK           KeyboardKey = 158 /* AC Back */
	kK_FORWARD        KeyboardKey = 159 /* AC Forward */
	kK_CLOSECD        KeyboardKey = 160
	kK_EJECTCD        KeyboardKey = 161
	kK_EJECTCLOSECD   KeyboardKey = 162
	kK_NEXTSONG       KeyboardKey = 163
	kK_PLAYPAUSE      KeyboardKey = 164
	kK_PREVIOUSSONG   KeyboardKey = 165
	kK_STOPCD         KeyboardKey = 166
	kK_RECORD         KeyboardKey = 167
	kK_REWIND         KeyboardKey = 168
	kK_PHONE          KeyboardKey = 169 /* Media Select Telephone */
	kK_ISO            KeyboardKey = 170
	kK_CONFIG         KeyboardKey = 171 /* AL Consumer Control Configuration */
	kK_HOMEPAGE       KeyboardKey = 172 /* AC Home */
	kK_REFRESH        KeyboardKey = 173 /* AC Refresh */
	kK_EXIT           KeyboardKey = 174 /* AC Exit */
	kK_MOVE           KeyboardKey = 175
	kK_EDIT           KeyboardKey = 176
	kK_SCROLLUP       KeyboardKey = 177
	kK_SCROLLDOWN     KeyboardKey = 178
	kK_KPLEFTPAREN    KeyboardKey = 179
	kK_KPRIGHTPAREN   KeyboardKey = 180
	kK_NEW            KeyboardKey = 181 /* AC New */
	kK_REDO           KeyboardKey = 182 /* AC Redo/Repeat */

	kK_F13 KeyboardKey = 183
	kK_F14 KeyboardKey = 184
	kK_F15 KeyboardKey = 185
	kK_F16 KeyboardKey = 186
	kK_F17 KeyboardKey = 187
	kK_F18 KeyboardKey = 188
	kK_F19 KeyboardKey = 189
	kK_F20 KeyboardKey = 190
	kK_F21 KeyboardKey = 191
	kK_F22 KeyboardKey = 192
	kK_F23 KeyboardKey = 193
	kK_F24 KeyboardKey = 194

	kK_PLAYCD         KeyboardKey = 200
	kK_PAUSECD        KeyboardKey = 201
	kK_PROG3          KeyboardKey = 202
	kK_PROG4          KeyboardKey = 203
	kK_DASHBOARD      KeyboardKey = 204 /* AL Dashboard */
	kK_SUSPEND        KeyboardKey = 205
	kK_CLOSE          KeyboardKey = 206 /* AC Close */
	kK_PLAY           KeyboardKey = 207
	kK_FASTFORWARD    KeyboardKey = 208
	kK_BASSBOOST      KeyboardKey = 209
	kK_PRINT          KeyboardKey = 210 /* AC Print */
	kK_HP             KeyboardKey = 211
	kK_CAMERA         KeyboardKey = 212
	kK_SOUND          KeyboardKey = 213
	kK_QUESTION       KeyboardKey = 214
	kK_EMAIL          KeyboardKey = 215
	kK_CHAT           KeyboardKey = 216
	kK_SEARCH         KeyboardKey = 217
	kK_CONNECT        KeyboardKey = 218
	kK_FINANCE        KeyboardKey = 219 /* AL Checkbook/Finance */
	kK_SPORT          KeyboardKey = 220
	kK_SHOP           KeyboardKey = 221
	kK_ALTERASE       KeyboardKey = 222
	kK_CANCEL         KeyboardKey = 223 /* AC Cancel */
	kK_BRIGHTNESSDOWN KeyboardKey = 224
	kK_BRIGHTNESSUP   KeyboardKey = 225
	kK_MEDIA          KeyboardKey = 226

	kK_SWITCHVIDEOMODE KeyboardKey = 227 /* Cycle between available video
	   outputs (Monitor/LCD/TV-out/etc) */
	kK_KBDILLUMTOGGLE KeyboardKey = 228
	kK_KBDILLUMDOWN   KeyboardKey = 229
	kK_KBDILLUMUP     KeyboardKey = 230

	kK_SEND        KeyboardKey = 231 /* AC Send */
	kK_REPLY       KeyboardKey = 232 /* AC Reply */
	kK_FORWARDMAIL KeyboardKey = 233 /* AC Forward Msg */
	kK_SAVE        KeyboardKey = 234 /* AC Save */
	kK_DOCUMENTS   KeyboardKey = 235

	kK_BATTERY KeyboardKey = 236

	kK_BLUETOOTH KeyboardKey = 237
	kK_WLAN      KeyboardKey = 238
	kK_UWB       KeyboardKey = 239

	kK_UNKNOWN KeyboardKey = 240

	kK_VIDEO_NEXT       KeyboardKey = 241 /* drive next video source */
	kK_VIDEO_PREV       KeyboardKey = 242 /* drive previous video source */
	kK_BRIGHTNESS_CYCLE KeyboardKey = 243 /* brightness up, after max is min */
	kK_BRIGHTNESS_AUTO  KeyboardKey = 244 /* Set Auto Brightness: manual
	brightness control is off,
	rely on ambient */
	kK_BRIGHTNESS_ZERO KeyboardKey = kK_BRIGHTNESS_AUTO
	kK_DISPLAY_OFF     KeyboardKey = 245 /* display device to off state */

	kK_WWAN   KeyboardKey = 246 /* Wireless WAN (LTE, UMTS, GSM, etc.) */
	kK_WIMAX  KeyboardKey = kK_WWAN
	kK_RFKILL KeyboardKey = 247 /* Key that controls all radios */

	kK_MICMUTE KeyboardKey = 248 /* Mute / unmute the microphone */
)
